name: Default
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: export
      - run: perl -v
      - run: apt update && apt install cpanminus
      - run: cpanm App::mymeta_requires
      - run: perl Makefile.PL
      - run: mymeta-requires | cpanm
      - run: make
      - run: make test
      - run: make dist
